# Generated by Django 3.0.8 on 2020-07-07 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('sub_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('posted_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_posted_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('posted_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_posted_by_user', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='core.Question')),
            ],
        ),
    ]
