# Generated by Django 3.0.8 on 2020-07-21 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staytuned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sub_text',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
